### ISSUE TITLE
data

### ISSUE THREAD

**Issue by bio-cscs** [miramou/pe_cfrna#2]
Dear authors, thank you very much for your time.
Could you please upload the processed data (data/rnaseq_stanford_all/* and data/delvecchio_data/*) ?
BTW, why both logCPM_postQC and TMM_postQC.csv are used in model training process? Could you please tell how to find or generate TMM postQC files?

**Comment by miramou** [comment]
Hi Tim - Thank you for your interest in the work.

You can find instructions on where to find data here - https://github.com/miramou/pe_cfrna
As for the logCPM_postQC and TMM_postQC files - you do not need both files; the TMM file path is ignored because `is_logCPM_path_R = True`. 

You can see the class definition for rnaseq_data which rnaseq_and_meta_data (a wrapper for the rnaseq and meta data classes) pulls from here - https://github.com/miramou/pe_cfrna/blob/master/analysis/util/class_def/obj_classes.py. Lines of interest would be 57-60 where you'll see that if is_logCPM_path_R is True then logCPM is populated from the passed in csv ("logCPM_postQC").

**Comment by miramou** [comment]
Hi Tim - If it's still useful, you can find the processed files for data/rnaseq_stanford_all/* on GEO> Here's a [link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE192902) for where to download (GEO ID = GSE192902). I also recently submitted an update to GEO to include the TMM files and logCPM_postQC_RemovedBatch.csv referenced in the second cell [here](https://github.com/miramou/pe_cfrna/blob/master/analysis/3.0_ML_Training.ipynb) and in other notebooks. 

The GEO submission already included as part of manuscript publication the processed counts tables (i.e., htseq_postQC.csv and htseq_merged.csv for each dataset).

As for data/delvecchio_data/*, our processed files are attached. As noted in the paper, we downloaded raw sequencing reads from the SRA.

Mira

[delvecchio_processed_as_in_our_manuscript.zip](https://github.com/miramou/pe_cfrna/files/15342377/delvecchio_processed_as_in_our_manuscript.zip)
